In [39]:

import pandas as pd
from scipy import stats
import numpy as np
import pandas as pd
import matplotlib as plt

In [40]:
ramen_ratings = pd.read_csv("ramen-ratings.csv")
ramen_ratings.head()

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN

In [41]:
# Remove the rows with missing data
clean_ramen = ramen_ratings.dropna(how="any")
clean_ramen.count()

Review #    41
Brand       41
Variety     41
Style       41
Country     41
Stars       41
Top Ten     41
dtype: int64

In [42]:
ramen_ratings['Brand'].count

<bound method Series.count of 0            New Touch
1             Just Way
2               Nissin
3              Wei Lih
4       Ching's Secret
             ...
2575             Vifon
2576           Wai Wai
2577           Wai Wai
2578           Wai Wai
2579          Westbrae
Name: Brand, Length: 2580, dtype: object>

In [43]:
ramen_ratings['Brand'].agg

<bound method Series.aggregate of 0            New Touch
1             Just Way
2               Nissin
3              Wei Lih
4       Ching's Secret
             ...
2575             Vifon
2576           Wai Wai
2577           Wai Wai
2578           Wai Wai
2579          Westbrae
Name: Brand, Length: 2580, dtype: object>

In [44]:
ramen_ratings.loc['Ratings'] :10

In [50]:
clean_ramen .sort_values('Stars', ascending=False)

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
616,1964,MAMA,Instant Noodles Coconut Milk Flavour,Pack,Myanmar,5,2016 #10
1757,823,Paldo,Kokomen Spicy Chicken,Pack,South Korea,5,2013 #9
1382,1198,Samyang Foods,Maesaengyitangmyun Baked Noodle,Pack,South Korea,5,2014 #5
633,1947,Prima Taste,Singapore Laksa Wholegrain La Mian,Pack,Singapore,5,2016 #1
1493,1087,MyKuali,Penang White Curry Noodle,Pack,Malaysia,5,2014 #1
1588,992,Prima Taste,Singapore Laksa La Mian,Pack,Singapore,5,2013 #1
1589,991,Prima Taste,Singapore Curry La Mian,Pack,Singapore,5,2013 #2
1646,934,Nongshim,Jinjja Jinjja Flamin' Hot & Nutty,Pack,USA,5,2013 #4
1846,734,Indomie,Mi Goreng Rasa Ayam Panggang Jumbo (Local),Pack,Indonesia,5,\n
1278,1302,Mama,Instant Noodles Yentafo Tom Yum Mohfai Flavour,Pack,Thailand,5,2014 #10
1865,715,Indomie,Mi Goreng Rendang (Import),Pack,Indonesia,5,2013 #3
1972,608,Koka,Spicy Black Pepper,Pack,Singapore,5,2012 #10
2188,392,Nissin,Yakisoba Noodles Karashi,Tray,Japan,5,2012 #3
2475,105,Indomie,Special Fried Curly Noodle,Pack,Indonesia,5,2012 #1
2533,47,Indomie,Mi Goreng Jumbo Barbecue Chicken,Pack,Indonesia,5,2012 #2
2535,45,Indomie,Mi Goreng Sate,Pack,Indonesia,5,\n
1309,1271,Prima Taste,Singapore Chilli Crab La Mian,Pack,Singapore,5,2014 #8
1397,1183,Paldo,Cheese Noodle,Pack,South Korea,5,2014 #6
1272,1308,Nongshim,Soon Veggie Noodle Soup,Pack,South Korea,5,2014 #9
995,1585,CarJEN,Nyonya Curry Laksa,Pack,Malaysia,5,2015 #4
655,1925,Prima,Juzz's Mee Creamy Chicken Flavour,Pack,Singapore,5,2016 #8
673,1907,Prima Taste,Singapore Curry Wholegrain La Mian,Pack,Singapore,5,2016 #5
752,1828,Tseng Noodles,Scallion With Sichuan Pepper Flavor,Pack,Taiwan,5,2016 #9
891,1689,Wugudaochang,Tomato Beef Brisket Flavor Purple Potato Noodle,Pack,China,5,2016 #7
1250,1330,Sapporo Ichiban,Otafuku Okonomi Sauce Yakisoba,Tray,Japan,5,2014 #4
963,1617,MyKuali,Penang Hokkien Prawn Noodle (New Improved Taste),Pack,Malaysia,5,2015 #7
942,1638,A-Sha Dry Noodle,Veggie Noodle Tomato Noodle With Vine Ripened ...,Pack,Taiwan,5,2015 #10
1059,1521,Maruchan,Gotsumori Sauce Yakisoba,Tray,Japan,5,2015 #9
1072,1508,Mamee,Chef Gold Recipe Mi Kari Seribu Rasa,Pack,Malaysia,5,2015 #6
1080,1500,MyKuali,Penang Red Tom Yum Goong Noodle,Pack,Malaysia,5,2015 #1
1109,1471,Mama,Instant Noodles Shrimp Creamy Tom Yum Flavour ...,Pack,Thailand,5,2013 #10
1114,1466,Mama,Oriental Style Instant Noodles Green Curry Fla...,Pack,Thailand,5,2015 #8
1230,1350,Mamee,Chef Curry Laksa Flavour,Pack,Malaysia,5,2014 #7
2567,13,Sapporo Ichiban,Chow Mein,Pack,Japan,5,2012 #4
2002,578,Nongshim,Shin Ramyun Black,Pack,South Korea,4.75,2012 #7
2146,434,Mi Sedaap,Kari Spesial,Pack,Indonesia,4.5,2012 #5
2295,285,Doll,Artificial Chicken,Pack,Hong Kong,4.5,2012 #9
1670,910,Paldo,Namja Ramyun,Bowl,South Korea,4.25,\n
2189,391,Myojo,Hyoubanya No Chukasoba Oriental,Pack,Japan,4.25,2012 #6
2549,31,Myojo,Ippeichan Yakisoba,Tray,Japan,4,2013 #6
2248,332,Nongshim,Champong Oriental Noodles,Cup,South Korea,3.75,\n

In [52]:
#US brands

Japan_ramen = clean_ramen.loc[clean_ramen ["Country"] == "Japan", :]
Japan_ramen.head()

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
1059,1521,Maruchan,Gotsumori Sauce Yakisoba,Tray,Japan,5,2015 #9
1250,1330,Sapporo Ichiban,Otafuku Okonomi Sauce Yakisoba,Tray,Japan,5,2014 #4
2188,392,Nissin,Yakisoba Noodles Karashi,Tray,Japan,5,2012 #3
2189,391,Myojo,Hyoubanya No Chukasoba Oriental,Pack,Japan,4.25,2012 #6
2549,31,Myojo,Ippeichan Yakisoba,Tray,Japan,4,2013 #6

In [71]:
# Sort based upon multiple columns
Brand = Japan_ramen.sort_values(["Stars", "Brand"])
Brand.head()

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
2549,31,Myojo,Ippeichan Yakisoba,Tray,Japan,4,2013 #6
2189,391,Myojo,Hyoubanya No Chukasoba Oriental,Pack,Japan,4.25,2012 #6
1059,1521,Maruchan,Gotsumori Sauce Yakisoba,Tray,Japan,5,2015 #9
2188,392,Nissin,Yakisoba Noodles Karashi,Tray,Japan,5,2012 #3
1250,1330,Sapporo Ichiban,Otafuku Okonomi Sauce Yakisoba,Tray,Japan,5,2014 #4

In [78]:
new_index = Japan_ramen.reset_index(drop = True)
new_index.head()

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,1521,Maruchan,Gotsumori Sauce Yakisoba,Tray,Japan,5,2015 #9
1,1330,Sapporo Ichiban,Otafuku Okonomi Sauce Yakisoba,Tray,Japan,5,2014 #4
2,392,Nissin,Yakisoba Noodles Karashi,Tray,Japan,5,2012 #3
3,391,Myojo,Hyoubanya No Chukasoba Oriental,Pack,Japan,4.25,2012 #6
4,31,Myojo,Ippeichan Yakisoba,Tray,Japan,4,2013 #6

In [102]:
#Breaki into bins by rating 
Japan_ramen = Japan_ramen.fillna("")
bins = [0,1.9,2.9,3.9,4.9,5.9]

groups = ["1","2","3","4","5"]

Japan_ramen['Ranking'] = pd.cut(Japan_ramen["Stars"], bins, labels=groups, include_lowest=True)
Japan_ramen
#ratings_binned.head()
#pd.cut(df["Test Score"], bins, labels=group_names, include_lowest=True)

TypeError: '<' not supported between instances of 'float' and 'str'

In [ ]:
##What is the top seeling brand by country? 
##By style?